# Here, we will see the basics about tensor flow

We are goin to cover:
* Introdutions to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function decorator to speed regular python functions
* Using GPU"s with tensorflow (TPU"s too)
* Exercices!

# Tensors

In [1]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.1


In [ ]:
# Create tensors with tf.constant() | This is not very comom, its like making a numpy array, usualy the data comes from somewhere
scalar = tf.constant(10)

# Check dimensions od the tensor
scalar.ndim

0

In [ ]:
# Create a vector
v = tf.constant([10, 10])

# Check the dimension
v.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10, 32],
                     [32, 10]])

matrix.ndim

2

In [ ]:
# Create a matrix specyfing the type
s_matrix = tf.constant([[32.1, 40.1],
                       [22.6, 3.1],
                       [56.2, 2.1]], dtype=tf.float16)

s_matrix.ndim

2

In [ ]:
# Lets make a tensor now!
tensor = tf.constant([
    [
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
     ],
    [
      [10, 11, 12],
      [13, 14, 15],
      [16, 17, 18]
     ],
    [
      [19, 20, 21],
      [22, 23, 24],
      [25, 26, 27]
     ],
])

tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int32)>

## Definitions

* Scalar: A number
* Vector: a scalar with direction
* Matrix: A 2-dim (x, and y) array of numbers
* Tensor: an n-dim array of numbers

## Making tensors with tf variable

In [2]:
# Create the same tensors as before with tf variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [3]:
# Let's try to change the changable tensor
changeable_tensor[0] = 7 # -> TypeError: 'ResourceVariable' object does not support item assignment[]

TypeError: 'ResourceVariable' object does not support item assignment

In [7]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [8]:
# Let's try to change the unchangeable tensor
unchangeable_tensor.assign(7) # -> AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

**Its possible to notice that there are two different types of tensors, the changeable ones, and the non-changeable ones. However, most of the times, tensor flow will decide wich tensor needs to be changed, and wich don't need to be changed. But google made these for a reason, even though its very rare that we code them yourself. Let"s see more about the uses if this tensor ahed!**

## Creating random tensors

**Random tensor are tensors with a random size, filled with random numbers**

These tensors are important because in the begging of a neural network, the initial weights are set randomly

In [10]:
# Create two random tensor
rd_1 = tf.random.Generator.from_seed(42)
rd_1 = rd_1.normal(shape=(3, 2))

rd_2 =  tf.random.Generator.from_seed(42)
rd_2 = rd_2.normal(shape=(3, 2))

rd_1 == rd_2 # They are the same!

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [12]:
# Lets shuffle the order of the elements in the tensor 
# (In the real world, this is important because you can have lots of problems by 
# feeding all of the supervised labels of type 1, and just after feeding the labels from type 2)
not_shuffled = tf.constant([
                            [32, 20],
                            [23, 21],
                            [32, 22]
                            ])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[32, 22],
       [32, 20],
       [23, 21]])>

#### 
🛠 Exercise: Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

In [18]:
# Random tensor 1

# Set global seed as 32
tf.random.set_seed(seed=32)
t1 = tf.random.uniform(shape=(10, 10))

# Here, in the same tensorflow version this tensor will repeat

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.54520595, 0.13372338, 0.45232666, 0.15582252, 0.9621073 ,
        0.8151462 , 0.4068215 , 0.9565903 , 0.5532354 , 0.44936454],
       [0.01469815, 0.86204493, 0.12014258, 0.91072273, 0.00848019,
        0.62772846, 0.8167286 , 0.98235905, 0.06410611, 0.17873585],
       [0.07358396, 0.95524645, 0.5906956 , 0.3774085 , 0.9427308 ,
        0.32449841, 0.05033565, 0.6481848 , 0.97997856, 0.7848562 ],
       [0.8223983 , 0.25406194, 0.21289039, 0.18566561, 0.18804717,
        0.5875702 , 0.45183384, 0.5508704 , 0.18366766, 0.55480397],
       [0.72248566, 0.66862214, 0.46865964, 0.50943816, 0.61882794,
        0.5858562 , 0.7246859 , 0.88589907, 0.7049539 , 0.00409675],
       [0.05000973, 0.3078189 , 0.58099496, 0.33607638, 0.16616762,
        0.9144434 , 0.5601578 , 0.4133414 , 0.9173528 , 0.60286224],
       [0.42348242, 0.34907532, 0.95223796, 0.7435889 , 0.45416832,
        0.10714757, 0.7326716 , 0.8436016 , 0.9553844 , 0.32

In [19]:
# Random tensor 2

# Set global seed as 32
tf.random.set_seed(seed=32)
t1 = tf.random.uniform(shape=(10, 10), seed=1)

# Here, this tensor will repeat across al tf versions and reruns of the program
t1

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.23868918, 0.2067703 , 0.54500055, 0.31111002, 0.39171076,
        0.31923223, 0.50584626, 0.18373597, 0.02248299, 0.04483771],
       [0.4144143 , 0.46722162, 0.51399994, 0.6130847 , 0.4647225 ,
        0.20000064, 0.76914823, 0.5839858 , 0.6873536 , 0.96707463],
       [0.48565722, 0.33153367, 0.47886515, 0.51659393, 0.05068457,
        0.60032547, 0.76667035, 0.70914185, 0.4547509 , 0.5271183 ],
       [0.04278278, 0.5251571 , 0.28889108, 0.6853919 , 0.39171982,
        0.8279501 , 0.16174483, 0.20636058, 0.3405305 , 0.11406171],
       [0.9386884 , 0.3217671 , 0.44583917, 0.23063862, 0.96298456,
        0.681301  , 0.09359741, 0.1416074 , 0.28955173, 0.6308347 ],
       [0.5590632 , 0.34686947, 0.5065472 , 0.7588887 , 0.81733704,
        0.13969612, 0.05073202, 0.2257644 , 0.41455007, 0.68057895],
       [0.99526405, 0.7197219 , 0.16188931, 0.0727433 , 0.90843403,
        0.7584722 , 0.73505676, 0.50471675, 0.3666612 , 0.06

In [21]:
# Random tensor 3

t3 = tf.random.uniform(shape=(10, 10))

# This tensor will probably never be the same
t3

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.20274532, 0.0362395 , 0.45186257, 0.72931254, 0.59773815,
        0.6252638 , 0.58525324, 0.68096423, 0.32602644, 0.01932275],
       [0.22446549, 0.37494373, 0.73189723, 0.88004696, 0.7486503 ,
        0.37286603, 0.79102564, 0.23662508, 0.46818578, 0.21304202],
       [0.14157367, 0.09235609, 0.9034941 , 0.77694905, 0.57940197,
        0.60302424, 0.8027278 , 0.92220044, 0.90689754, 0.38798702],
       [0.37056744, 0.27422643, 0.6186545 , 0.9105128 , 0.42198884,
        0.7742996 , 0.4347055 , 0.19009268, 0.90281   , 0.35568738],
       [0.9403497 , 0.21564186, 0.94391954, 0.15408313, 0.04337871,
        0.10940921, 0.4930966 , 0.34173262, 0.16191673, 0.10891414],
       [0.6980876 , 0.37882996, 0.21452188, 0.38206518, 0.21853375,
        0.8613732 , 0.12197328, 0.63633585, 0.9614316 , 0.73795223],
       [0.7060425 , 0.21180153, 0.9056978 , 0.00346363, 0.8909935 ,
        0.84277236, 0.65081537, 0.28079653, 0.02766383, 0.65

In [30]:
# Random tensor 4

# Set random operational seed
t4 = tf.random.uniform(shape=(10, 10), seed=1)

# This tensor will probably never be the same
t4

# This tensor will probably never be the same, because a random global seed is being picked on ever'y run

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0.43435204, 0.7643721 , 0.22755837, 0.25575662, 0.3266493 ,
        0.8570912 , 0.19885874, 0.11847687, 0.34247828, 0.04866219],
       [0.1764673 , 0.05280983, 0.6165079 , 0.16672444, 0.6740991 ,
        0.1210202 , 0.08165538, 0.4200238 , 0.7130655 , 0.13879728],
       [0.00240612, 0.44413483, 0.39974153, 0.50941944, 0.61840856,
        0.1297723 , 0.8713479 , 0.4490199 , 0.60107946, 0.67212164],
       [0.38352287, 0.40614486, 0.6388161 , 0.35023355, 0.6454948 ,
        0.3870709 , 0.31611717, 0.40493274, 0.9559287 , 0.8465743 ],
       [0.53566396, 0.08273423, 0.94358265, 0.12073255, 0.11923432,
        0.46973956, 0.6996037 , 0.1988877 , 0.48798954, 0.4532181 ],
       [0.45707238, 0.03657556, 0.6698524 , 0.40946555, 0.18064988,
        0.19896722, 0.44178808, 0.6653211 , 0.7065352 , 0.482082  ],
       [0.93641555, 0.3991722 , 0.02356648, 0.95567405, 0.24465477,
        0.24331975, 0.42625427, 0.73858976, 0.69852936, 0.93

**To resume: Shuffling and ussing seeds its important because the order on wich a nn is feeded is very important! And on most cases, if you want reproducibility in yours results, you need to set both global and local seeds (its possible to onyl set the global seed, but with the tensorflow version changes, the result will stop having reproducibility) | So, always set both global seed, and operational level seed!**

## Other ways to make tensors

In [32]:
tf.ones([4, 4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [33]:
tf.zeros((4, 4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Its possible to turn numpy arrays into tensors

The difference between arrays and tensors is that tensors can be run on a GPU

In [2]:
# Import numpy
import numpy as np

# Make numpy array
np_a = np.arange(1, 25, dtype=np.int32)

# Make a tensor with it
X = tf.constant(np_a, shape=(2, 3, 4)) # This divides the vector at n_a into a matrice with these dimensions, if the dimensions are less than np_a length, this will raise an exception
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

## Getting information from tensors:

* Shape (500 lines x 12 columns)
* Rank (The number of dimensions, 1 -> vector 2 -> matrix, n -> tensor)
* axis | dimension (You can acess all elements of a specific dimension, tensor[:, 0])
* size (The total number of items in the tensor)

In [80]:
# Create a rank for tensor
tensor = tf.zeros(shape=(2, 5, 5))

tensor.shape

TensorShape([2, 5, 5])

In [76]:
tensor[0] # First 5x5 tensor 
tensor[1] # Second 5x5 tensor 

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [77]:
tensor.ndim # Dimension (quantity of tensor), Dimension (quantity of lines), Dimension (quantity of columns)

3

In [84]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [86]:
print("Data type of tensor:", tensor.dtype)
print("Number of dimensions:", tensor.ndim)
print("Shape of tensor:", tensor.shape)
print("Elements along the 0 axis:", tensor.shape[0])
print("Elements along the last axis:", tensor.shape[-1])
print("Total of items in tensor:", tf.size(tensor).numpy())

Data type of tensor: <dtype: 'float32'>
Number of dimensions: 3
Shape of tensor: (2, 5, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total of items in tensor: 50


## Indexing tensor

In [90]:
# Get the first two elements of every tensor
tensor[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [107]:
# Get the first element from each dimension from each index, execept for the final one
tensor[:1, :1, :]

<tf.Tensor: shape=(1, 1, 5), dtype=float32, numpy=array([[[0., 0., 0., 0., 0.]]], dtype=float32)>

In [114]:
# Create a rank 2 tensor
t2 = tf.constant(value=[[1, 2], [3, 4]])
t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [123]:
t2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4])>

## Manipulating tensors

**Basic Operations:**
+, -, *, /

In [126]:
# Make a tensor
t = tf.constant([[10, 32], [23, 12]])

# You can add values to a tensor using the addition operator
t + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 42],
       [33, 22]])>

In [ ]:
# Make a tensor
t = tf.constant([[10, 32], [23, 12]])

# You can add values to a tensor using the addition operator
t + 10

In [127]:
# *
t * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 320],
       [230, 120]])>

In [128]:
# -
t - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 22],
       [13,  2]])>

In [129]:
# /
t / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 3.2],
       [2.3, 1.2]])>

In [130]:
# Making operations with tensorflow functions (Its better to use this if you have big tensors!)
tf.multiply(t, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 320],
       [230, 120]])>

## Matrix multiplication

For mathematical purposes, the are some rules that tensor need to follow:

1. The iiner dimensions must mactch
2. The resulting matris has the shape of the outer dimensions

In [137]:
tf.matmul(
    tf.constant([
        [1, 2, 5],
        [7, 2, 1],
        [3, 3, 3],
    ])

    ,

    tf.constant([
        [3, 5],
        [6, 7],
        [1, 8],
    ]) 
)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [138]:
tf.matmul(
    tf.constant([
        [1, 2],
        [7, 2],
        [3, 3],
    ])

    ,

    tf.constant([
        [3, 5],
        [6, 7],
        [1, 8],
    ]) 
)

# Thus givers a erros because the inner dimensions dont match 3x(2 != 3)x2

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [140]:
# Lets make a shape thhat can be multiplied
tf.matmul(
    tf.constant([
        [1, 2],
        [7, 2],
        [3, 3],
    ])

    ,

    tf.constant([
        [3, 5],
        [6, 7],
    ]) 
)

# Now the inner dimensions are equal! 3x(2 == 2)x2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 19],
       [33, 49],
       [27, 36]])>

In [147]:
# You can change a tensor to the size that you want using transpose or reshape
X = tf.constant([
    [1, 2],
    [7, 2],
    [3, 3],
])

In [149]:
# Reshape (Just makes the format and append the numbers in order)
tf.reshape(X, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 7],
       [2, 3, 3]])>

In [152]:
# Flips the matrix (rows turn into columns)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 7, 3],
       [2, 2, 3]])>

### Matrix multiplication is called dot product, and is made using matmul, but there is a method called tensordot

In [160]:
# Lets make two tensor that CANT be multiplied with matrix multiplication (they dont follow the necessary rules)
X = tf.constant([
    [1, 2],
    [2, 3],
    [3, 4],
])

Y = tf.constant([
    [2, 3],
    [5, 10],
    [5, 10],
])

try: 
    tf.matmul(X, Y)

except:
    print("This tensors cannot be multiplied with matrix multiplication")

This tensors cannot be multiplied with matrix multiplication


In [174]:
# Use tensor dot!
print("-X=" * 50)
print(tf.transpose(X))
print("=-=-==-" * 10)
print(Y)
print("-X=" * 50)
tf.tensordot(tf.transpose(X) # Use transpose to make this tensor follow the rule
, Y, axes=0)

-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=
tf.Tensor(
[[1 2 3]
 [2 3 4]], shape=(2, 3), dtype=int32)
=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-=-=-==-
tf.Tensor(
[[ 2  3]
 [ 5 10]
 [ 5 10]], shape=(3, 2), dtype=int32)
-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=-X=


<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[ 2,  3],
         [ 5, 10],
         [ 5, 10]],

        [[ 4,  6],
         [10, 20],
         [10, 20]],

        [[ 6,  9],
         [15, 30],
         [15, 30]]],


       [[[ 4,  6],
         [10, 20],
         [10, 20]],

        [[ 6,  9],
         [15, 30],
         [15, 30]],

        [[ 8, 12],
         [20, 40],
         [20, 40]]]])>

In [163]:
# Use tensor dot!
tf.matmul(tf.transpose(X) # Use transpose to make this tensor follow the rule
, Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[27, 53],
       [39, 76]])>

In [159]:
tf.tensordot(X # Use transpose to make this tensor follow the rule
, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[    25977,    142211,   5030760],
       [   685981,    498819, 142657444],
       [       71,      4467,      1466]])>

## Changing the data type of a tensor

In [3]:
# The default type is (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [4]:
# With int
C = tf.constant([7, 4])
C.dtype

tf.int32

In [6]:
# Change the precision of a tensor (from 32 to 16)
# This is very important, the tensor flow docs have guide to improve training
#  time in 60% just making these types of operation
C = tf.constant([7, 4])
C.dtype

tf.int32

In [7]:
# Change type with tf cast!
changed_C = tf.cast(C, dtype=tf.float16)
changed_C.dtype

tf.float16

## Tensor agreggations

min, max, avg

In [9]:
# Return absolute values
tensor = tf.constant([-23, 4, 1,2])
tf.abs(tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([23,  4,  1,  2])>

In [22]:
# Descriptive analytics
random_tensor = tf.constant(np.random.randint(0, 100, size=100000))

# min
print("Min:", tf.reduce_min(random_tensor))

# max
print("Max:", tf.reduce_max(random_tensor))

# mean
print("Mean:", tf.reduce_mean(random_tensor))

# sum
print("Sum:", tf.reduce_sum(random_tensor))

# standard variance
print("Variance:", np.array(random_tensor).var())

# standard deviation
print("Std:", np.array(random_tensor).std())

Min: tf.Tensor(0, shape=(), dtype=int32)
Max: tf.Tensor(99, shape=(), dtype=int32)
Mean: tf.Tensor(49, shape=(), dtype=int32)
Sum: tf.Tensor(4958085, shape=(), dtype=int32)
Variance: 828.5111032774998
Std: 28.78386880315952


## Find positional minimum and maximum
Imagine a set of prediciton probabilities, the neural network will have for example 0.70 of class 1 and 0.30 of class 2 | Its important to know how to select the high probability of a line, to know the classification!

In [29]:
# Create a tensor to text this
rt = tf.random.uniform(shape=[50])

# Find the positional max
tf.argmax(rt)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [30]:
# Find the positional min
tf.argmin(rt)

<tf.Tensor: shape=(), dtype=int64, numpy=29>

## Squeezing a tensor (removing all 1 dimension axes)

In [33]:
# Make a tensor
rt = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
rt.shape

TensorShape([1, 1, 1, 1, 50])

In [34]:
rt_squeezed = tf.squeeze(rt)
rt_squeezed.shape

TensorShape([50])

## One hot encoding

In [38]:
# Craete a list of indice
ll = [0, 1, 2, 3, 4, 5]

# One hot encode this list
tf.one_hot(ll, depth=len(ll), on_value=333, off_value=666)

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[333, 666, 666, 666, 666, 666],
       [666, 333, 666, 666, 666, 666],
       [666, 666, 333, 666, 666, 666],
       [666, 666, 666, 333, 666, 666],
       [666, 666, 666, 666, 333, 666],
       [666, 666, 666, 666, 666, 333]])>

## More math tensor flow operations

squaring, log, square root

In [44]:
# Make a tensor
H = tf.range(1, 10)

In [45]:
# Square root
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [47]:
# Find the loog (this is the natural loog)
tf.math.log(tf.cast(H, dtype=tf.float32)) # -> Necessary to cast to float32

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [48]:
# Find the square root
tf.math.sqrt(tf.cast(H, dtype=tf.float32)) # -> Necessary to cast to float32

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

## Exploring tensorflow and numpy compatibility

**tensorflow intercast well with numpy arrays**

In [49]:
J = tf.constant(np.array([[1, 2, 3], [4, 5, 6]]))
J # Array to tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [50]:
np.array(J) # Tensor to array

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
# Is this useful? Yes, if some action is not possible in tensorflow but possible in numpy you can always convert
np.array(J)[0][1:] # for example, array slicing

array([2, 3])

## How to use GPU"s? to process tensors

In [56]:
### Finding acess to GPUs
tf.config.list_physical_devices() # I only have a CPU available! :(

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

## Extra exercices!

In [62]:
# Vector
vector = tf.constant([1, 2])

# Scalar
scalar = tf.constant(10)

# Matrix
matrix = tf.constant([
                    [1, 2, 3],
                    [4, 5, 6]
                    ])

# Tensor
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
    ])

for v in [vector, scalar, matrix, tensor]:
    print(v.shape)
    print("=-=" * 15)

(2,)
=-==-==-==-==-==-==-==-==-==-==-==-==-==-==-=
()
=-==-==-==-==-==-==-==-==-==-==-==-==-==-==-=
(2, 3)
=-==-==-==-==-==-==-==-==-==-==-==-==-==-==-=
(2, 2, 3)
=-==-==-==-==-==-==-==-==-==-==-==-==-==-==-=


In [65]:
# Creating two tensor with random number betwen 0 and 1
uniform_tensor_1 = tf.random.uniform(shape=(5, 300), dtype=tf.float16)
uniform_tensor_2 = tf.random.uniform(shape=(5, 300), dtype=tf.float16)

In [70]:
# Multiply the two tensor with matrix multiplication
mm_tensor = tf.matmul(
    uniform_tensor_1, 
    tf.transpose(uniform_tensor_2) # --> Transpose to avoid error
)

mm_tensor

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[70.2 , 71.75, 67.25, 71.5 , 69.4 ],
       [75.75, 77.44, 75.2 , 76.  , 76.5 ],
       [77.56, 77.75, 75.8 , 73.9 , 78.  ],
       [70.3 , 70.8 , 67.56, 67.75, 70.44],
       [78.06, 79.7 , 75.56, 76.5 , 79.6 ]], dtype=float16)>

In [72]:
# Multiply the two tensor with dot product
mm_tensor = tf.tensordot(
    uniform_tensor_1, 
    tf.transpose(uniform_tensor_2), # --> Transpose to avoid error
    axes=0,
)

mm_tensor

<tf.Tensor: shape=(5, 300, 300, 5), dtype=float16, numpy=
array([[[[0.2563  , 0.5205  , 0.3801  , 0.6675  , 0.09    ],
         [0.595   , 0.0872  , 0.2067  , 0.8506  , 0.1561  ],
         [0.877   , 0.63    , 0.2443  , 0.655   , 0.1744  ],
         ...,
         [0.584   , 0.6973  , 0.2993  , 0.899   , 0.225   ],
         [0.2544  , 0.6978  , 0.09094 , 0.213   , 0.3774  ],
         [0.8364  , 0.7715  , 0.584   , 0.743   , 0.587   ]],

        [[0.0881  , 0.179   , 0.1307  , 0.2295  , 0.03093 ],
         [0.2046  , 0.02998 , 0.07104 , 0.2922  , 0.05365 ],
         [0.3015  , 0.2166  , 0.084   , 0.2251  , 0.05997 ],
         ...,
         [0.2008  , 0.2396  , 0.1029  , 0.309   , 0.07733 ],
         [0.08746 , 0.2399  , 0.03125 , 0.07324 , 0.1298  ],
         [0.2876  , 0.2651  , 0.2008  , 0.2554  , 0.2017  ]],

        [[0.2195  , 0.446   , 0.3257  , 0.572   , 0.0771  ],
         [0.51    , 0.07477 , 0.177   , 0.7285  , 0.1338  ],
         [0.7515  , 0.5396  , 0.2092  , 0.561   , 0.1495

In [75]:
# Make a tensor with dim 3
uniform_tensor_3 = tf.random.uniform(shape=(224, 224, 3), dtype=tf.float16)

In [81]:
# Finf the maximum value of the first axis
tf.reduce_max(uniform_tensor_3[0, 0, :])

<tf.Tensor: shape=(), dtype=float16, numpy=0.909>

In [82]:
# Find the minimum value of the first axis
tf.reduce_min(uniform_tensor_3[0, 0, :])

<tf.Tensor: shape=(), dtype=float16, numpy=0.5625>

In [85]:
# Create a tensor and squeeze it
uniform_tensor_4 = tf.random.uniform(shape=(1, 224, 224, 3), dtype=tf.float16)

# Squeeze
uniform_tensor_4 = tf.squeeze(uniform_tensor_4)
uniform_tensor_4.shape

TensorShape([224, 224, 3])

In [100]:
# Create a tensor with size 10 and finx max value of it
uniform_tensor_5 = tf.constant(value=[1, 2, 99, 1, 5, 3, 3, 5, 1, 1], shape=(10))

ind = tf.argmax(uniform_tensor_5)

uniform_tensor_5[ind] # -> max value

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [103]:
# One hot encode a tensor
one_hot_tensor = tf.one_hot(uniform_tensor_5, depth=len(uniform_tensor_5), on_value=1, off_value=-99)

one_hot_tensor

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[-99,   1, -99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99,   1, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99, -99, -99],
       [-99,   1, -99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99,   1, -99, -99, -99, -99],
       [-99, -99, -99,   1, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99,   1, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99,   1, -99, -99, -99, -99],
       [-99,   1, -99, -99, -99, -99, -99, -99, -99, -99],
       [-99,   1, -99, -99, -99, -99, -99, -99, -99, -99]])>